version: '3.8'

services:
  todo_db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d todo_db"]
      interval: 10s
      retries: 5
      start_period: 5s

  person_service:
    build:
      context: .
    container_name: person_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo_db:5432/todo_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      todo_db:
        condition: service_healthy
    restart: unless-stopped