services:
  person_service:
    image: openjdk:17-jdk-slim
    container_name: TODO
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo_db:5432/todo_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - todo_db

  todo_db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"