spring:
  application:
    name: TODO

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
#    url: jdbc:postgresql://todo_db:5432/todo_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.davidenko.TODO: DEBUG